services:

  postgres: # add _db change name
    image: postgres:18
    container_name: history_weather
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data:/data                    # local only, gitignored + TO BE REMOVED BEFORE COMMIT + SAME BELOW
      - ./data:/docker-entrypoint-initdb.d  # local only, gitignored - Postgres automatically runs any .sql file placed in that folder on startup
      #- ./init-scripts:/docker-entrypoint-initdb.d  
    # Port to be able to use pgAdmin
    ports:
      -   "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  init:
    image: postgres:18
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./auto_run_script.sh:/auto_run_script.sh
      - ./init-scripts:/init-scripts
    entrypoint: ["bash", "/auto_run_script.sh"]

  fastapi:  #app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
